<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Lokad.ContentAddr.Azure</AssemblyName>
    <RuntimeIdentifiers>win</RuntimeIdentifiers>
    <OutputType>Library</OutputType>
    <Company>Lokad</Company>
    <Copyright>Copyright © Lokad 2024</Copyright>

    <AssemblyVersion>3.1.4.0</AssemblyVersion>
    <FileVersion>3.1.4</FileVersion>
    <PackageId>Lokad.ContentAddr.Azure</PackageId>
    <PackageVersion>3.1.4</PackageVersion>
    <LangVersion>latest</LangVersion>
    <Version>3.1.4</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageIcon>lokad.png</PackageIcon>
    <PackageProjectUrl>https://github.com/Lokad/ContentAddr.Azure</PackageProjectUrl>
    <Description>Azure Blob Storage support for Lokad.ContentAddr</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    <PackageReference Include="Lokad.ContentAddr" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\lokad.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
  
</Project>